((magit-branch nil)
 (magit-commit nil)
 (magit-dispatch nil)
 (magit-pull nil)
 (magit-push nil)
 (magit-revert
  ("--edit"))
 (rg-menu
  ("--context=5" "--type-not=ts")
  ("--context=5")
  ("--context=5" "--type-not=.ts")
  ("--context=5" "--max-columns=10" "--type-not=.ts")
  ("--multiline-dotall --multiline" "--context=5"))
 (transient:rg-menu:--context= "5")
 (transient:rg-menu:--max-columns= "10")
 (transient:rg-menu:--type-not= "ts" ".ts"))
