;;; Automatically generated by ‘recentf’ on Fri Sep  3 13:47:39 2021.

(setq recentf-list
      '(
        "/root/.config/emacs/Emacs.org"
        "/mnt/fesp/fespbi/.browserslistrc"
        "/mnt/fesp/fespbi/PHP/FespbiController.php"
        "/mnt/fesp/fespbi/src/composables/axiosPost.ts"
        "/root/.config/emacs/var/bookmark-default.el"
        "/root/mountShared.sh"
        "/mnt/fesp2/fespbi/PHP/FespbiController.php"
        "/opt/lampp/htdocs/Projects/fespbi/PHP/test4.php"
        "/mnt/fesp2/fespbi/PHP/test4.php"
        "/mnt/fesp2/fespbi/PHP/test2.php"
        "/mnt/fesp2/fespbi/src/views/SalesExports.vue"
        "/mnt/fesp2/fespbi/src/components/SelectDialog.vue"
        "/mnt/fesp2/fespbi/src/components/ArgumentsList.vue"
        "/mnt/fesp2/fespbi/src/components/FilterTable.vue"
        "/mnt/fesp2/fespbi/src/components/PaginatedFilterTable.vue"
        "/mnt/fesp2/fespbi/src/views/SalesTrends.vue"
        "/mnt/fesp2/fespbi/src/views/ReportDashboard.vue"
        "/mnt/fesp2/fespbi/src/App.vue"
        "/opt/lampp/htdocs/Projects/fespbi/src/components/MultiSelect.vue"
        "/mnt/fesp2/fespbi/src/components/MultiSelect.vue"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
