;;; Automatically generated by ‘recentf’ on Tue Aug 31 18:14:08 2021.

(setq recentf-list
      '(
        "/root/.config/emacs/Emacs.org"
        "/root/.nix-dotfiles/home-manager/flake.nix"
        "/root/.config/emacs/var/bookmark-default.el"
        "/root/.nix-dotfiles/home-manager/modules/config/emacs/history"
        "/root/.config/emacs/org/Notes.org"
        "/root/.config/emacs/org/Tasks.org"
        "/root/.config/emacs/org/Journal.org"
        "/root/.config/emacs/org/Projects/emacs.org"
        "/root/.config/emacs/org/Projects/Stock.org"
        "/root/.config/emacs/org/Projects/ApiOrders.org"
        "/root/.config/emacs/org/Projects/.nix-dotfiles.org"
        "/nix/store/lssrpjrfywp6hmjb19m72nk62f7j6fjr-emacs-pgtkgcc-20210816.0/share/emacs/28.0.50/etc/NEWS"
        "/root/.nix-dotfiles/home-manager/modules/config/emacs/Emacs.org"
        "/root/.nix-dotfiles/home-manager/modules/config/emacs/gnu.png"
        "/root/.nix-dotfiles/home-manager/flake.lock"
        "/root/Documents/test.php"
        "/root/.config/emacs/etc/yasnippet/snippets/php-mode/pr"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
