;;; Automatically generated by ‘recentf’ on Mon Aug 30 02:28:08 2021.

(setq recentf-list
      '(
        "/root/.nix-dotfiles/home-manager/modules/config/shell/profile"
        "/root/.nix-dotfiles/home-manager/flake.nix"
        "/root/.nix-dotfiles/nixos/flake.nix"
        "/root/.nix-dotfiles/home-manager/modules/nixos-desktop.nix"
        "/root/Documents/test.vue"
        "/root/.config/emacs/Emacs.org"
        "/root/Documents/test.py"
        "/nix/store/lssrpjrfywp6hmjb19m72nk62f7j6fjr-emacs-pgtkgcc-20210816.0/share/emacs/28.0.50/etc/NEWS"
        "/root/Documents/test.php"
        "/root/.config/xmonad/xmonad.hs"
        "/root/.config/emacs/var/auto-save/sessions/1275-nixos-desktop~"
        "/root/.config/emacs/etc/Notes/Roam/20210826164148-test.org"
        "/root/.config/emacs/etc/Notes/Roam/daily/2021-08-26.org"
        "/root/.config/emacs/history"
        "/root/.config/emacs/OrgFiles/Journal.org"
        "/root/.config/emacs/.gitignore"
        "/root/.config/emacs/OrgFiles/Tasks.org"
        "/root/.nix-dotfiles/home-manager/modules/home-manager.nix"
        "/tmp/py-shell-completion-setup-code.py"
        "/root/.nix-dotfiles/home-manager/modules/config/xmonad/xmonad.hs"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
