;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(magit-revision-history file-name-history minibuffer-history buffer-name-history extended-command-history empty-history consult-imenu--history consult--line-history))
(setq file-name-history '("~/.config/emacs/.gitignore" "~/.config/emacs/Emacs.org" "~/Documents/test.php" "~/Documents/test.py" "~/.config/emacs/temp.el" "~/.nix-dotfiles/home-manager/modules/config/xmonad/xmonad.hs" "~/.config/emacs/elpa/orderless-20210812.2035/orderless.el" "/nix/store/lssrpjrfywp6hmjb19m72nk62f7j6fjr-emacs-pgtkgcc-20210816.0/share/emacs/28.0.50/src/TAGS" "~/.nix-dotfiles/home-manager/modules/config/emacs/OrgFiles/Tasks.org" "~/.config/emacs/OrgFiles/Tasks.org" "~/.config/emacs/elpa/popup-kill-ring-20131020.1854/popup-kill-ring.el" "~/.nix-dotfiles/home-manager/modules/config/emacs/straight/repos/embark/embark.el" "~/.config/emacs/straight/build/embark/embark.el" "/nix/store/lssrpjrfywp6hmjb19m72nk62f7j6fjr-emacs-pgtkgcc-20210816.0/share/emacs/28.0.50/src/minibuf.c" "/nix/store/lssrpjrfywp6hmjb19m72nk62f7j6fjr-emacs-pgtkgcc-20210816.0/share/emacs/28.0.50/lisp/emacs-lisp/nadvice.el.gz" "/nix/store/lssrpjrfywp6hmjb19m72nk62f7j6fjr-emacs-pgtkgcc-20210816.0/share/emacs/28.0.50/lisp/TAGS"))
(setq minibuffer-history '("savehist-file" "prescient-save-file"))
(setq buffer-name-history '(".gitignore" "emacs" "test.php" "test.py"))
(setq extended-command-history '("emacs-version"))
(setq consult--line-history '("company"))
(setq projectile-project-command-history '#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ()))
